spring:
  datasource:
    url: jdbc:mysql://101.33.211.193:3306/admin?allowMultiQueries=true&useUnicode=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: eden
    password: y%^N&4by9k2XLD5S
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:  
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: 101.33.211.193
    port: 6379
    timeout: 5000
    password: kif&37Jcr8NP%ftV
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0